project:
  title: "Preprint"
  render:
    - index.qmd
  output-dir: docs

site-url: https://mvuorre.github.io/funky-firefly
repo-url: https://github.com/mvuorre/funky-firefly
osf-url: https://osf.io/
preprint-url: https://osf.io/preprints/psyarxiv/

format:
  html:
    toc: true
    fontsize: 14pt
    other-links: 
      - text: Preprint (PsyArXiv)
        href: https://
        icon: file-pdf
      - text: Online supplement
        href: https://mvuorre.github.io/funky-firefly
        icon: globe2
      - text: GitHub Repository
        href: https://osf.io/
        icon: github
      - text: OSF Repository
        href: https://github.com/mvuorre/funky-firefly
        icon: archive
  preprint-typst:
    output-file: ms.pdf
    fontsize: 11pt
    mainfont: Libertinus Serif
  preprint-docx:
    output-file: ms.docx

execute:
  freeze: auto
